FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /miniCalculator

COPY . .

RUN dotnet publish -c Release
# multi-stage build: muiltiple base images
FROM mcr.microsoft.com/dotnet/aspnet:6.0
# pull another image
WORKDIR /miniCalculator
COPY --from=build /App/bin/Release/net6.0/publish/ .

ENTRYPOINT [ "dotnet", "miniCalculator.dll" ]